FROM <%= @distribution %>:<%= @tag %>
MAINTAINER <%= @maintainer %>

<%- if @debootstrap -%>
# don't mount /proc and /sys because Docker already does that, and blows up if
# you try to do it
RUN sed -i "s%.*mount -t \\(proc\\|sysfs\\) .*%%" /debootstrap/functions && \
    /debootstrap/debootstrap --second-stage
<%- end -%>

RUN groupadd -r whalebuilder && \
    useradd -r -g whalebuilder -d /home/whalebuilder -m whalebuilder
WORKDIR /home/whalebuilder

<%- if @repository -%>
RUN sed -i "s/http:\\/\\/http\\(redir.debian.org\\|.debian.net\\)\\/debian/<%= @repository.gsub(/\//, "\\\\\\\\/") %>/" \
        /etc/apt/sources.list
<%- end -%>

RUN apt-get update
<% @hooks.each do |hook| -%>
<%= hook %>
<% end -%>
RUN apt-get install -y --no-install-recommends build-essential fakeroot
