FROM <%= @distribution %>:<%= @tag %>
MAINTAINER <%= @maintainer %>

<%- if @debootstrap -%>
RUN /sbin/cdebootstrap-foreign
<%- end -%>

RUN groupadd -r whalebuilder && \
    useradd -r -g whalebuilder -d /home/whalebuilder -m whalebuilder
WORKDIR /home/whalebuilder

<%- if @repository -%>
RUN sed -i "s/http:\\/\\/http\\(redir.debian.org\\|.debian.net\\)\\/debian/<%= @repository.gsub(/\//, "\\\\\\\\/") %>/" \
        /etc/apt/sources.list
<%- end -%>

RUN apt-get update && apt-get install -y --no-install-recommends build-essential fakeroot
