FROM <%= @basename %>

<%- @hooks.each do |hook| -%>
<%= hook %>
<%- end -%>

COPY whalebuilder-dependency-helper_1.0_*.deb <%= @extra_debs.join(" ") %> /home/whalebuilder/

RUN dpkg -i --force-depends --force-conflicts /home/whalebuilder/whalebuilder-dependency-helper_1.0_*.deb <%= (@extra_debs.map { |x| "/home/whalebuilder/" + x }).join(" ") %> && \
    rm /home/whalebuilder/whalebuilder-dependency-helper_1.0_*.deb <%= (@extra_debs.map { |x| "/home/whalebuilder/" + x }).join(" ") %>
RUN apt-get update && apt-get install -f -y --no-install-recommends && apt-get clean
RUN install -o whalebuilder -g whalebuilder -d /build
