.TH WHALEBUILDER 1 "2015-03-29"
.SH NAME
whalebuilder \- Debian package builder using Docker
.SH SYNOPSIS
.B whalebuilder
[globalopts]
<command>
[options]
.SH DESCRIPTION
.I Whalebuilder
is a tool for building Debian packages in a minimal environment using
.I Docker
to manage the build environment.  For more information, see
/usr/share/doc/whalebuilder/README.md.
.SH BUGS
.PP
This is a terrible manpage.
.SH SEE ALSO
.PP
.IR docker (1)
.SH VERSION
This man page is from
.I Whalebuilder
version 0.1.
.SH AUTHOR
Hubert Chathi, \fBhubert@uhoreg.ca\fP.
